package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gemma_stub",
    srcs = ["gemma_model_constraint_provider.cc"],
    hdrs = ["//runtime/components/constrained_decoding:gemma_model_constraint_provider.h"],
    deps = [
        "//runtime/components/constrained_decoding:constraint_provider",
    ],
)
